class Autogenerated {
  String total;
  String grandTotal;
  List<BillSummary> billSummary;
  Header header;
  List<Item> item;
  Settings settings;

  Autogenerated(
      {this.total,
      this.grandTotal,
      this.billSummary,
      this.header,
      this.item,
      this.settings});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    total = json['Total'];
    grandTotal = json['GrandTotal'];
    if (json['BillSummary'] != null) {
      billSummary = <BillSummary>[];
      json['BillSummary'].forEach((v) {
        billSummary.add(new BillSummary.fromJson(v));
      });
    }
    header =
        json['Header'] != null ?new Header.fromJson(json['Header']) : null;
    if (json['Item'] != null) {
      item = <Item>[];
      json['Item'].forEach((v) {
        item.add(new Item.fromJson(v));
      });
    }
    settings = json['Settings'] != null ?
         new Settings.fromJson(json['Settings'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Total'] = this.total;
    data['GrandTotal'] = this.grandTotal;
    if (this.billSummary != null) {
      data['BillSummary'] = this.billSummary.map((v) => v.toJson()).toList();
    }
    if (this.header != null) {
      data['Header'] = this.header.toJson();
    }
    if (this.item != null) {
      data['Item'] = this.item.map((v) => v.toJson()).toList();
    }
    if (this.settings != null) {
      data['Settings'] = this.settings.toJson();
    }
    return data;
  }
}

class BillSummary {
  String key;
  String value;

  BillSummary({this.key, this.value});

  BillSummary.fromJson(Map<String, dynamic> json) {
    key = json['key'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['key'] = this.key;
    data['value'] = this.value;
    return data;
  }
}

class Header {
  String hotelName;
  String phone;
  String currency;
  String address;
  String address1;
  String address2;
  String billNo;
  String dateOfBill;
  String timeOfBill;
  String orderType;
  String table;
  String fssaiNo;
  String gSTNo;
  String customerRemarks;
  String orderNote;

  Header(
      {this.hotelName,
      this.phone,
      this.currency,
      this.address,
      this.address1,
      this.address2,
      this.billNo,
      this.dateOfBill,
      this.timeOfBill,
      this.orderType,
      this.table,
      this.fssaiNo,
      this.gSTNo,
      this.customerRemarks,
      this.orderNote});

  Header.fromJson(Map<String, dynamic> json) {
    hotelName = json['HotelName'];
    phone = json['Phone'];
    currency = json['currency'];
    address = json['Address'];
    address1 = json['Address1'];
    address2 = json['Address2'];
    billNo = json['BillNo'];
    dateOfBill = json['DateOfBill'];
    timeOfBill = json['TimeOfBill'];
    orderType = json['OrderType'];
    table = json['Table'];
    fssaiNo = json['FssaiNo'];
    gSTNo = json['GSTNo'];
    customerRemarks = json['CustomerRemarks'];
    orderNote = json['OrderNote'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['HotelName'] = this.hotelName;
    data['Phone'] = this.phone;
    data['currency'] = this.currency;
    data['Address'] = this.address;
    data['Address1'] = this.address1;
    data['Address2'] = this.address2;
    data['BillNo'] = this.billNo;
    data['DateOfBill'] = this.dateOfBill;
    data['TimeOfBill'] = this.timeOfBill;
    data['OrderType'] = this.orderType;
    data['Table'] = this.table;
    data['FssaiNo'] = this.fssaiNo;
    data['GSTNo'] = this.gSTNo;
    data['CustomerRemarks'] = this.customerRemarks;
    data['OrderNote'] = this.orderNote;
    return data;
  }
}

class Item {
  String no;
  String itemAmt;
  String itemName;
  String alternateName;
  String itemaddons;
  String qty;
  String menuNote;
  String rate;
  List<String> modifiers;
  String printerName;

  Item(
      {this.no,
      this.itemAmt,
      this.itemName,
      this.alternateName,
      this.itemaddons,
      this.qty,
      this.menuNote,
      this.rate,
      this.modifiers,
      this.printerName});

  Item.fromJson(Map<String, dynamic> json) {
    no = json['No'];
    itemAmt = json['ItemAmt'];
    itemName = json['ItemName'];
    alternateName = json['alternate_name'];
    itemaddons = json['itemaddons'];
    qty = json['Qty'];
    menuNote = json['menu_note'];
    rate = json['Rate'];
    modifiers = json['modifiers'].cast<String>();
    printerName = json['printer_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['No'] = this.no;
    data['ItemAmt'] = this.itemAmt;
    data['ItemName'] = this.itemName;
    data['alternate_name'] = this.alternateName;
    data['itemaddons'] = this.itemaddons;
    data['Qty'] = this.qty;
    data['menu_note'] = this.menuNote;
    data['Rate'] = this.rate;
    data['modifiers'] = this.modifiers;
    data['printer_name'] = this.printerName;
    return data;
  }
}

class Settings {
  String printerName;
  String printerType;
  String customerNo;
  int itemLength;
  String printLogo;
  String qrPathContent;
  String thankYouNote;
  String vatTitle;
  String vatNo;
  String invoiceNo;
  String saleDate;
  String salesMan;
  String customerName;
  String customerPhone;
  String customerAddress;
  String paymentName;
  String waiterName;
  String thankYouNote2;
  String eIDRMK;
  String printType;
  String pageSize;
  String autoPrintKot;
  String autoPrintBot;

  Settings(
      {this.printerName,
      this.printerType,
      this.customerNo,
      this.itemLength,
      this.printLogo,
      this.qrPathContent,
      this.thankYouNote,
      this.vatTitle,
      this.vatNo,
      this.invoiceNo,
      this.saleDate,
      this.salesMan,
      this.customerName,
      this.customerPhone,
      this.customerAddress,
      this.paymentName,
      this.waiterName,
      this.thankYouNote2,
      this.eIDRMK,
      this.printType,
      this.pageSize,
      this.autoPrintKot,
      this.autoPrintBot});

  Settings.fromJson(Map<String, dynamic> json) {
    printerName = json['PrinterName'];
    printerType = json['PrinterType'];
    customerNo = json['customer_no'];
    itemLength = json['ItemLength'];
    printLogo = json['PrintLogo'];
    qrPathContent = json['qr_path_content'];
    thankYouNote = json['ThankYouNote'];
    vatTitle = json['vat_title'];
    vatNo = json['vat_no'];
    invoiceNo = json['invoice_no'];
    saleDate = json['sale_date'];
    salesMan = json['sales_man'];
    customerName = json['customer_name'];
    customerPhone = json['customer_phone'];
    customerAddress = json['customer_address'];
    paymentName = json['payment_name'];
    waiterName = json['waiter_name'];
    thankYouNote2 = json['ThankYouNote2'];
    eIDRMK = json['EIDRMK'];
    printType = json['PrintType'];
    pageSize = json['PageSize'];
    autoPrintKot = json['auto_print_kot'];
    autoPrintBot = json['auto_print_bot'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['PrinterName'] = this.printerName;
    data['PrinterType'] = this.printerType;
    data['customer_no'] = this.customerNo;
    data['ItemLength'] = this.itemLength;
    data['PrintLogo'] = this.printLogo;
    data['qr_path_content'] = this.qrPathContent;
    data['ThankYouNote'] = this.thankYouNote;
    data['vat_title'] = this.vatTitle;
    data['vat_no'] = this.vatNo;
    data['invoice_no'] = this.invoiceNo;
    data['sale_date'] = this.saleDate;
    data['sales_man'] = this.salesMan;
    data['customer_name'] = this.customerName;
    data['customer_phone'] = this.customerPhone;
    data['customer_address'] = this.customerAddress;
    data['payment_name'] = this.paymentName;
    data['waiter_name'] = this.waiterName;
    data['ThankYouNote2'] = this.thankYouNote2;
    data['EIDRMK'] = this.eIDRMK;
    data['PrintType'] = this.printType;
    data['PageSize'] = this.pageSize;
    data['auto_print_kot'] = this.autoPrintKot;
    data['auto_print_bot'] = this.autoPrintBot;
    return data;
  }
}
